# docker-compose up -d
#
#
version: "2.1"

services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
    volumes:
      - ./media/transmission/config:/config
      - ./media/transmission/downloads:/downloads

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - ./media/radarr/config:/config
      - ./media/radarr/movies:/movies
      - ./media/transmission/downloads:/downloads
    depends_on:
      - transmission

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - ./media/sonarr/config:/config
      - ./media/sonarr/series:/tv
      - ./media/transmission/downloads:/downloads
    depends_on:
      - transmission

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - ./media/jackett/config:/config
      - ./media/transmission/downloads:/downloads
    depends_on:
      - transmission

  plex:
    image: linuxserver/plex
    container_name: plex
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - ./media/radarr/movies:/movies
      - ./media/sonarr/series:/tv
      - ./media/plex/config:/config
      - /tmp/transcode:/transcode
    depends_on:
      - transmission
      - sonarr
      - radarr
