# docker-compose up -d
#
# update images + deploy:
# docker-compose up --force-recreate --build -d
# docker image prune -f
#
# mkdir -p DATA_STORAGE_DIR/{torrents,media/{tv,movies}}
# mkdir -p DOCKER_STORAGE_DIR/{radarr,sonarr,prowlarr,plex,transmission}
#
# sudo chown -R dockermedia:users DATA_STORAGE_DIR DOCKER_STORAGE_DIR
# sudo chmod -R a=,a+rX,u+w,g+w DATA_STORAGE_DIR DOCKER_STORAGE_DIR
#
version: "3.0"

services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    ports:
      - 9091:9091
    environment:
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - CREATE_TUN_DEVICE=true
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_STORAGE_DIR}/torrents:/data
      - ${DOCKER_STORAGE_DIR}/transmission:/config

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
      - AUTO_UPDATE=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_STORAGE_DIR}/prowlarr:/config

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_STORAGE_DIR}/radarr:/config
      - ${DATA_STORAGE_DIR}:/data
    depends_on:
      - transmission
      - prowlarr

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_STORAGE_DIR}/sonarr:/config
      - ${DATA_STORAGE_DIR}:/data
    depends_on:
      - transmission
      - prowlarr

  plex:
    image: linuxserver/plex
    container_name: plex
    #devices:
    #  - /dev/dri:/dev/dri
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_STORAGE_DIR}/plex:/config
      - ${DATA_STORAGE_DIR}/media:/data/media
    #  - /tmp/transcode:/transcode
