# docker-compose up -d
#
# update images + deploy:
# docker-compose pull
# docker-compose up -d --remove-orphans
# docker image prune -f
#
# mkdir -p DATA_STORAGE_DIR/{torrents,media/{tv,movies}}
# mkdir -p DOCKER_STORAGE_DIR/{radarr,sonarr,prowlarr,plex,transmission,ombi,rdtclient}
# mkdir /tmp/transcode
#
# sudo chown -R dockermedia:users DATA_STORAGE_DIR DOCKER_STORAGE_DIR
# sudo chmod -R a=,a+rX,u+w,g+w DATA_STORAGE_DIR DOCKER_STORAGE_DIR
# sudo chown -R dockermedia:users /tmp/transcode
# sudo chmod -R a=,a+rX,u+w,g+w /tmp/transcode
# 
version: "3.1"

services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    ports:
      - 9091:9091
    environment:
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - TRANSMISSION_DOWNLOAD_DIR=/data/torrents
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
      - CREATE_TUN_DEVICE=true
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_STORAGE_DIR}/torrents:/data/torrents
      - ${DOCKER_STORAGE_DIR}/transmission:/data/transmission-home

  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    restart: unless-stopped
    ports:
      - 6500:6500
    logging:
       driver: json-file
       options:
          max-size: 10m
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - ${DOCKER_STORAGE_DIR}/rdtclient:/data/db
      - ${DATA_STORAGE_DIR}/torrents:/data/downloads
    depends_on:
      - transmission

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
      - AUTO_UPDATE=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_STORAGE_DIR}/prowlarr:/config

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_STORAGE_DIR}/radarr:/config
      - ${DATA_STORAGE_DIR}:/data
    depends_on:
      - transmission
      - prowlarr

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_STORAGE_DIR}/sonarr:/config
      - ${DATA_STORAGE_DIR}:/data
    depends_on:
      - transmission
      - prowlarr

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    ports:
      - 3579:3579
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
      - BASE_URL=/ombi #optional
    volumes:
      - ${DOCKER_STORAGE_DIR}/ombi:/config
    depends_on:
      - sonarr
      - radarr

  plex:
    image: linuxserver/plex
    container_name: plex
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_STORAGE_DIR}/plex:/config
      - ${DATA_STORAGE_DIR}/media:/data/media
      - /tmp/transcode:/transcode
