# to run: docker-compose run
#
#
version: "2"

services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: always
    networks:
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
    volumes:
      - ./media/transmission/config/:/config
      - ./media/transmission/downloads/:/downloads

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    networks:
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - ./media/radarr/config:/config
      - ./media/radarr/movies:/movies
      - ./media/transmission/downloads:/downloads
    depends_on:
      - transmission-openvpn

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    networks:
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - ./media/sonarr/config:/config
      - ./media/sonarr/series:/tv
      - ./media/transmission/downloads:/downloads
    depends_on:
      - transmission-openvpn

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    networks:
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - ./media/jackett/config:/config
      - ./media/transmission/downloads:/downloads
    depends_on:
      - transmission-openvpn

  plex:
    image: linuxserver/plex
    container_name: plex
    restart: always
    networks:
      - web
    environment:
      - PLEX_UID=${USER_ID}
      - PLEX_GID=${GROUP_ID}
      - TZ=${TZ_LOCAL}
    volumes:
      - ./media/radarr/movies:/data/movies
      - ./media/sonarr/series:/data/tvshows
      - ./media/plex/config/:/config
      - /tmp/transcode/:/transcode
    depends_on:
      - transmission-openvpn
      - sonarr
      - radarr

networks:
  web:
    external: true
